### ISSUE TITLE
Running the exe

### ISSUE THREAD

**Issue by TaserTheFox** [JyGein/JyGeins-KTANE-Solvers#1]
Do you just need to download just the exe file? or the entire source code? 
This would be a helpful note if added to the ReadMe file.

**Comment by JyGein** [comment]
Yeah to run the program you just need to download the exe

**Comment by TaserTheFox** [comment]
well, uh, command like closed immediately, maybe its something to do with `sys.path.insert(0, r'C:\Users\jygei\Desktop\ktane autosolvers\code\modules')` contained within "JyGeins KTANE solvers.py"?

**Comment by JyGein** [comment]
hmmmmm yeah it probably is looking for that folder on your system? i may have found a solution though i dont really know lmao

**Comment by JyGein** [comment]
i created a branch to test some stuff out

**Comment by JyGein** [comment]
something is not working, ill have to check back tmmr

**Comment by JyGein** [comment]
the solution might be to not do —one-file when compiling it ill have to try that

**Comment by JyGein** [comment]
yeah you gotta have the folder of modules aswell rip, though added those to the releases
